### ISSUE TITLE
`messari gen` to generate spkg from ABI

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/substreams#115]
The purpose of this command line option is to generate a "default" substreams module for any given ABI, such that it'll stream the events defined in the ABI.

For example, given the Uniswap v2 Factory contract, this command should generate an spkg with the following protobuf:

```protobuf
// event PairCreated(address indexed token0, address indexed token1, address pair);
message PairCreatedEvent {
  string contract_address = 1;
  string tx_hash = 2;
  uint32 log_index = 3;
  uint32 block_number = 4;
  uint64 block_time = 5;
  
  string token0 = 10;
  string token1 = 11;
  string pair = 12;
}
```

and the following module:
```
  - name: store_pair_created_events
    kind: store
    updatePolicy: set
    valueType: proto:messari.uniswap.v2.PairCreatedEvent
    initialBlock: 10000835
    inputs:
      - source: sf.ethereum.type.v2.Block
```
